; Configuracion de la INSTALACION 

nombre = "desarrollo"
id_grupo_desarrollo = "0"
clave_querystring = "3b2b64cb544f7c1c230de28853d2b50e"
clave_db = "32067d41c9fa059c189e62e9dc2d45c6"
editor_php = "start"
url = "/toba_2.7"
es_produccion = "0"
;autenticacion = "toba|openid|ldap|cas|saml|saml_onelogin"
;session_name = "TOBA_SESSID"
