; Configuracion de la INSTANCIA 

base = "toba_2_7"
proyectos = "toba_editor, toba_referencia, toba_usuarios, comunidades"
tipo = "normal"

[toba_editor]
path = "C:\ServidorWeb\comunidades\vendor\siu-toba\framework/proyectos/toba_editor"
url = "/toba_editor/2.7"

[toba_referencia]
path = "C:\ServidorWeb\comunidades\vendor\siu-toba\framework/proyectos/toba_referencia"
url = "/toba_referencia/2.7"

[toba_usuarios]
path = "C:\ServidorWeb\comunidades\vendor\siu-toba\framework/proyectos/toba_usuarios"
url = "/toba_usuarios/2.7"

[comunidades]
path = "C:\ServidorWeb\comunidades\src"
url = "/comunidades/1.0"
